name: Release

on:
  push:
    # Use push on master event to run workflow instead of pull_request
    # closed (merged) event because github token doesn't have write permission
    # for pull_request from fork repository.
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    types:
      - labeled

jobs:
  pre-release:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Fetch the next version by dry-running bumpr
      - name: Bump version
        id: bumpr-dry
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1
        with:
          dry_run: true

      # Overwrite next version in ./VERSION
      - name: Write version in ./VERSION
        uses: DamianReeves/write-file-action@master
        with:
          path: ./VERSION
          contents: |
            ${{ steps.bumpr-dry.outputs.next_version }}
          write-mode: overwrite

      # Use the REST API to commit changes, so we get automatic commit signing
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: VERSION
          DESTINATION_BRANCH: master
        run: |
          export TODAY=$( date -u '+%Y-%m-%d' )
          export MESSAGE="chore: generate $FILE_TO_COMMIT for $TODAY"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"

  release:
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
      # Bump version on merging Pull Requests with specific labels. (bump:major,bump:minor,bump:patch)
      - name: Bump version
        id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1

      # Get tag name.
      - name: Get tag name
        id: tag
        uses: haya14busa/action-cond@v1
        with:
          cond: "${{ startsWith(github.ref, 'refs/tags/') }}"
          if_true: ${{ github.ref }}
          if_false: ${{ steps.bumpr.outputs.next_version }}

      # Create release.
      - name: Create release
        uses: actions/create-release@v1
        if: "steps.tag.outputs.value != ''"
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.value }}
          release_name: Project Clover ${{ steps.tag.outputs.value }}
          body: ${{ steps.bumpr.outputs.message }}
          draft: false
          prerelease: false

  release-check:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Post bumpr status comment
      - name: Check release
        uses: haya14busa/action-bumpr@v1
